[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/fortytw2/dockertest"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "6.14.3"

[[constraint]]
  name = "github.com/go-playground/validator"
  version = "9.20.2"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.5"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
